set nocompatible


source $VIMRUNTIME/vimrc_example.vim

source $VIMRUNTIME/mswin.vim

behave mswin


set number

set nowrap

set guifont=DejaVu_Sans_Mono


set tabstop=4

set shiftwidth=4

set softtabstop=4

set expandtab

" OSX only
"set transparency=10

autocmd BufWritePre <buffer> :%s/\s\+$//e


set lines=74 columns=133


colorscheme slate


set viminfo='0,:0,<0,@0,f0,/0


set diffexpr=MyDiff()

function MyDiff()

  let opt = '-a --binary '

  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif

  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif

  let arg1 = v:fname_in

  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif

  let arg2 = v:fname_new

  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif

  let arg3 = v:fname_out

  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif

  if $VIMRUNTIME =~ ' '

    if &sh =~ '\<cmd'

      if empty(&shellxquote)

        let l:shxq_sav = ''

        set shellxquote&

      endif

      let cmd = '"' . $VIMRUNTIME . '\diff"'

    else

      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'

    endif

  else

    let cmd = $VIMRUNTIME . '\diff'

  endif

  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3

  if exists('l:shxq_sav')

    let &shellxquote=l:shxq_sav

  endif

endfunction


set backup

" Win only
set backupdir=C:\\Temp
set dir=C:\\Temp
" OSX only
"set backupdir=/tmp
"set dir=/tmp

set noundofile

autocmd FileType text set textwidth=0
